name: Build and Test

on:
  push:
    branches:
      - HU-22
      - develop
      - cover
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies in frontend
        working-directory: ./frontend
        run: yarn
      - name: Install dependencies in root
        working-directory: ./
        run: yarn
      - name: Test and Coverage
        working-directory: ./frontend
        run: yarn jest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
